project:
  type: website

website:
  title: "mapineqpy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reference/index.qmd
        text: API Reference
    right:
      - icon: github
        href: "https://github.com/e-kotov/mapineqpy"

metadata-files:
  - "reference/_sidebar.yml"

format:
  html:
    default-image-extension: ""
    theme: cosmo
    css:
      - "reference/_styles-quartodoc.css"
    include-in-header:
      - text: |
          <script data-goatcounter="https://jukadipos.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
          <script src="https://cdn.counter.dev/script.js" data-id="7e3e8d31-9a84-48b0-a678-a00715236a90" data-utcoffset="1"></script>
          <script>
            (function(h,o,t,j,a,r){
                h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
                h._hjSettings={hjid:3578286,hjsv:6};
                a=o.getElementsByTagName('head')[0];
                r=o.createElement('script');r.async=1;
                r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
                a.appendChild(r);
            })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
          </script>

quartodoc:
  package: mapineqpy
  dir: reference
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css
  sections:
    - title: "Core Functions"
      desc: "Functions for accessing Mapineq API."
      contents:
        - sources
        - source_coverage
        - source_filters
        - data
        - nuts_levels
    - title: "Options"
      desc: "Configuration options."
      contents:
        - options
