# source_filters { #mapineqpy.source_filters }

`source_filters`



## Functions

| Name | Description |
| --- | --- |
| [source_filters](#mapineqpy.source_filters.source_filters) | Fetch possible filtering values for a given source, year, and NUTS level. |

### source_filters { #mapineqpy.source_filters.source_filters }

```python
source_filters.source_filters(
    source_name,
    year,
    level,
    filters=None,
    limit=2500,
)
```

Fetch possible filtering values for a given source, year, and NUTS level.

Args:
    source_name (str): The name of the data source (f_resource).
    year (int): The year for filtering.
    level (str): The NUTS level ("0", "1", "2", "3").
    filters (dict, optional): A dictionary where the keys are filter fields and
                              values are the selected filter values. Default is None.
    limit (int): Maximum number of results to fetch. Default is 2500.

Returns:
    pd.DataFrame: A DataFrame with fields, labels, and their possible values for filtering:
        - field: Filter field name.
        - field_label: Filter field label.
        - label: Value label.
        - value: Value.